name: update

on:
  workflow_dispatch:

  schedule: 
    - cron:  '30 16 1,16 * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run scripts
        run:
          scripts/make.sh

      - name: Add changed files
        run:
          git add .

      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update ${{ steps.date.outputs.date }}"
